"""empty message

Revision ID: 001ea50dab9e
Revises: 757df778092d
Create Date: 2022-10-13 19:17:17.556488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001ea50dab9e'
down_revision = '757df778092d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('postmark_message_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'postmark_message_id')
    # ### end Alembic commands ###
