"""empty message

Revision ID: 344486ad9208
Revises: ba720f26a071
Create Date: 2022-10-15 06:27:44.608251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344486ad9208'
down_revision = 'ba720f26a071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batches', 'templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'template_id')
    # ### end Alembic commands ###
