"""empty message

Revision ID: 757df778092d
Revises: 
Create Date: 2022-10-13 18:53:53.330813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757df778092d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('postmark_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_to', sa.String(length=120), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=False),
    sa.Column('email_opened', sa.Boolean(), nullable=True),
    sa.Column('email_clicked', sa.Boolean(), nullable=True),
    sa.Column('email_template_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_template_version'], ['email_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('email_versions')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
