"""empty message

Revision ID: af04514faac6
Revises: 
Create Date: 2022-10-14 22:41:11.918553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af04514faac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pm_templates',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pm_template_version',
    sa.Column('postmark_template_id', sa.Integer(), nullable=False),
    sa.Column('postmark_template_alias', sa.String(), nullable=True),
    sa.Column('postmark_template_subject', sa.String(), nullable=True),
    sa.Column('postmark_template_htmlbody', sa.String(), nullable=True),
    sa.Column('postmark_template_textbody', sa.String(), nullable=True),
    sa.Column('postmark_template_type', sa.String(), nullable=True),
    sa.Column('postmark_layout_template', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['template_name'], ['pm_templates.name'], ),
    sa.PrimaryKeyConstraint('postmark_template_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_to', sa.String(length=120), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=False),
    sa.Column('email_opened', sa.Boolean(), nullable=True),
    sa.Column('email_clicked', sa.Boolean(), nullable=True),
    sa.Column('postmark_message_id', sa.String(), nullable=True),
    sa.Column('email_template_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_template_version'], ['pm_template_version.postmark_template_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('pm_template_version')
    op.drop_table('pm_templates')
    # ### end Alembic commands ###
