"""empty message

Revision ID: ba720f26a071
Revises: 
Create Date: 2022-10-15 06:07:12.876271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba720f26a071'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_of_emails', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('date_sent', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_transactions',
    sa.Column('postmark_message_id', sa.String(), nullable=False),
    sa.Column('sent_to', sa.String(length=120), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=False),
    sa.Column('email_opened', sa.Boolean(), nullable=True),
    sa.Column('email_clicked', sa.Boolean(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('postmark_message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_transactions')
    op.drop_table('templates')
    op.drop_table('batches')
    # ### end Alembic commands ###
